"""Type stubs for sims4.resources -- resource type enums and keys."""

from enum import IntEnum
from typing import Any


class Types(IntEnum):
    """Resource type identifiers used by InstanceManager."""
    TRAIT = ...
    BUFF = ...
    INTERACTION = ...
    OBJECT = ...
    SIM_INFO = ...
    SITUATION = ...
    ASPIRATION = ...
    CAREER = ...
    SKILL = ...
    LOT_TUNING = ...
    RECIPE = ...
    STATISTIC = ...
    RELATIONSHIP_BIT = ...
    SNIPPET = ...
    ACTION = ...
    REWARD = ...
    SPELL = ...


class ResourceKey:
    """A (type, group, instance) tuple identifying a game resource."""
    type: Types
    group: int
    instance: int

    def __init__(self, type: Types, group: int, instance: int) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
