"""Type stubs for the top-level services module.

The game exposes ``import services`` as a namespace of factory functions
that return singleton managers.  These stubs cover the most commonly
accessed managers.
"""

from typing import Any, Optional, Iterator

from sims4.resources import Types


# ── Manager Return Types ────────────────────────────────────────────────

class _SimInfoManager:
    def get_all(self) -> Iterator[Any]: ...
    def get(self, sim_id: int) -> Optional[Any]: ...
    def instanced_sims_gen(self) -> Iterator[Any]: ...

class _HouseholdManager:
    def get_all(self) -> Iterator[Any]: ...
    def get(self, household_id: int) -> Optional[Any]: ...

class _ObjectManager:
    def get_all(self) -> Iterator[Any]: ...
    def get(self, object_id: int) -> Optional[Any]: ...

class _ClientManager:
    def get_first_client(self) -> Optional[Any]: ...

class _InstanceManager:
    TYPE: Types
    _tuned_classes: dict[int, Any]
    def get(self, tuning_id: int) -> Optional[Any]: ...
    @property
    def types(self) -> dict[int, Any]: ...

class _StoryProgressionService:
    ACTIONS: tuple[Any, ...]

class _Zone:
    id: int
    world_id: int
    lot: Any
    def do_zone_spin_up(self) -> None: ...
    def on_loading_screen_animation_finished(self) -> None: ...
    def on_cleanup_zone_objects(self) -> None: ...


# ── Service Accessors ───────────────────────────────────────────────────

def sim_info_manager() -> Optional[_SimInfoManager]: ...
def household_manager() -> Optional[_HouseholdManager]: ...
def object_manager() -> Optional[_ObjectManager]: ...
def client_manager() -> Optional[_ClientManager]: ...
def current_zone() -> Optional[_Zone]: ...
def active_household() -> Optional[Any]: ...
def active_household_id() -> int: ...
def get_instance_manager(resource_type: Types) -> Optional[_InstanceManager]: ...
def get_story_progression_service() -> Optional[_StoryProgressionService]: ...
def time_service() -> Optional[Any]: ...
def calendar_service() -> Optional[Any]: ...
