"""Type stubs for sims.* game modules -- Sim, SimInfo, Household, Funds."""

from enum import IntEnum
from typing import Any, Optional, Iterator, List


# ── sims.sim_info_types ─────────────────────────────────────────────────

class Age(IntEnum):
    """Sim age stages."""
    BABY = ...
    INFANT = ...
    TODDLER = ...
    CHILD = ...
    TEEN = ...
    YOUNGADULT = ...
    ADULT = ...
    ELDER = ...


class Species(IntEnum):
    """Sim species."""
    HUMAN = ...
    DOG = ...
    CAT = ...
    FOX = ...
    HORSE = ...


class Gender(IntEnum):
    """Sim gender."""
    MALE = ...
    FEMALE = ...


# ── sims.sim_info.SimInfo ───────────────────────────────────────────────

class TraitTracker:
    equipped_traits: List[Any]
    bypass_blacklisted: bool

    def has_trait(self, trait: Any) -> bool: ...
    def add_trait(self, trait: Any) -> bool: ...
    def remove_trait(self, trait: Any) -> bool: ...


class PregnancyTracker:
    def update_pregnancy(self) -> None: ...


class SimInfo:
    sim_id: int
    first_name: str
    last_name: str
    age: Age
    species: Species
    gender: Gender
    household_id: int
    household: Any  # Household
    trait_tracker: TraitTracker
    pregnancy_tracker: PregnancyTracker
    is_played_sim: bool
    lod: Any

    def advance_age(self) -> None: ...
    def get_name(self) -> str: ...
    def is_baby(self) -> bool: ...
    def is_child(self) -> bool: ...
    def is_teen(self) -> bool: ...
    def is_young_adult(self) -> bool: ...
    def is_adult(self) -> bool: ...
    def is_elder(self) -> bool: ...
    def is_on_active_lot(self) -> bool: ...


# ── sims.sim.Sim ────────────────────────────────────────────────────────

class Sim:
    sim_id: int
    sim_info: SimInfo

    def on_add(self) -> None: ...
    def on_remove(self) -> None: ...


# ── sims.household.Household ────────────────────────────────────────────

class Household:
    id: int
    name: str
    funds: '_Funds'
    home_zone_id: int

    def sim_info_gen(self) -> Iterator[SimInfo]: ...
    @property
    def is_played_household(self) -> bool: ...


# ── sims.funds._Funds ──────────────────────────────────────────────────

class FundsReason(IntEnum):
    """Reason codes for Simoleon transactions."""
    CAREER = ...
    OBJECT_PURCHASE = ...
    LOT_PURCHASE = ...
    CHEAT = ...
    BILLS = ...
    RETAIL = ...
    TELEMETRY = ...
    FUNDS_TRANSFER = ...


class _Funds:
    _household: Household
    money: int

    def add(
        self,
        amount: int,
        reason: Optional[FundsReason] = ...,
        sim: Optional[Any] = ...,
    ) -> None: ...

    def try_remove(
        self,
        amount: int,
        reason: Optional[FundsReason] = ...,
        sim: Optional[Any] = ...,
    ) -> bool: ...
